-- 添加用户资料字段
ALTER TABLE users
ADD COLUMN IF NOT EXISTS name VARCHAR(100),
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS avatar TEXT;

-- 添加备注说明
COMMENT ON COLUMN users.name IS '用户名称';
COMMENT ON COLUMN users.bio IS '用户简介';
COMMENT ON COLUMN users.avatar IS '用户头像URL';

